version: '1'

services:
  db:
    image: 'postgres:latest'
    ports:
      - 15432:5432
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "securepassword"
    networks:
      - postgres-network
    volumes:
      - ./db-data/:/var/lib/postgresql/data/

  pgadmin:
    user: root
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@example.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
      PGADMIN_LISTEN_PORT: 9000
    ports:
      - 15433:9000
    depends_on:
      - db
    volumes:
      - ./pgadmin-data/:/var/lib/pgadmin/
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge
