// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

type Author struct {
	ID   int32
	Name string
}

type Book struct {
	ID          int32
	AuthorID    int32
	Title       string
	Description string
}

type Role struct {
	ID   int32
	Name string
}

type User struct {
	ID           int32
	UserName     string
	PasswordHash string
}

type Userrole struct {
	ID     int32
	UserID int32
	RoleID int32
}
